### ISSUE TITLE
 Is there a way to edit the game's bitmap font and then pack it back as before?

### ISSUE THREAD

**Issue by lngdao** [VriskaSerket51/EastwardPacker#1]
It may not seem related, but I want to localize the game's language. And I found the game text in the locale.g file but had problems with the font. It seems the font uses a "pixel operator" bitmap font. I have localized this font but don't know how to pack it back into the font.g file. Would appreciate if you know something

**Comment by VriskaSerket51** [comment]
Yes, "PixelOperator.fnt" is right one. You might also edit "zipex.fnt" for quick dialog.

You can pack font.g with Eastwardlib.g

i.e.
```cs
using EastwardLib.Assets;
using EastwardLib.MetaData;

var g = GArchive.Read("font.g");
// 1579e05ecb12c339177083f481e227f1 is for PixelOperator.fnt
g["font/1579e05ecb12c339177083f481e227f1"] = new TextAsset("... font data").Encode();
// 1579e05ecb12c339177083f481e227f1 is for PixelOperator_0.png
g["font/d11a88ad4c5e632b960927b559a60522"] = new HmgAsset(Image.FromFile("... font image path")).Encode();

// Same for zipex

g.Write("locale_new.g");
```

**Comment by lngdao** [comment]
I did it. Your stuff is amazing, tksm @VriskaSerket51

**Comment by zouk211** [comment]
I reopened it because I had something to ask. I found the text I want to translate in the binary file "ccddffae68787606e5b0332355ec8fa2" in the script.g file. Is there any way to do that? Thank you

**Comment by VriskaSerket51** [comment]
That's precompiled Lua file, which is compiled by LuaJIT.
Well, you can decompile it, edit, and compile again. There are some tools like luajit-decompiler.
Or maybe EastwardMod might be the one. I'll update tool in somedays.

**Comment by zouk211** [comment]
@VriskaSerket51 Yes, i decompile it by using [luajit-decompiler-v2](https://github.com/marsinator358/luajit-decompiler-v2) and edit, and compile again by use LuaJIT. And i use your lib to put it back

```
// script.g
byte[] binaryData = File.ReadAllBytes(scriptPath);
g["script/ccddffae68787606e5b0332355ec8fa2"] = new BinaryAsset(binaryData).Encode();

g.Write(targetOutPath);
```

But the game crashes as soon as it is turned on. Am I doing wrong somewhere? Thank u

**Comment by VriskaSerket51** [comment]
I think you can just insert raw code.

**Comment by VriskaSerket51** [comment]
Did it work?

**Comment by zouk211** [comment]
sorry, recently I've been busy with other work, it worked like a charm, thanks for that. And I want to ask something. Do you know this font and its fnt file name?

![d1e377d188a857513f4f3f0125fafa71](https://github.com/VriskaSerket51/EastwardPacker/assets/88200574/58159043-b0ab-4f09-bdba-569fdbbf11e8)
![image](https://github.com/VriskaSerket51/EastwardPacker/assets/88200574/e1610d65-71fc-4f16-9fb1-63f1277ea46d)

**Comment by VriskaSerket51** [comment]
Yup, it's called QuickDialog, and it uses the font 'zipex'.
- zipex.fnt: font/90a0a0edd55111a0830b919e386a5fa3
- zipex_0.png: font/db2d1fe734f4ef54efd8970a9be8560f
